[package]
name = "naivecoin"
version = "0.1.0"
authors = ["Alexander Lenhardt <alexander.lenhardt@soundcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockchain = {path = "blockchain" }
